global:
  scrape_interval: 15s  # How often to scrape targets by default.
  evaluation_interval: 15s  # How often to evaluate rules.

scrape_configs:
  # Scrape configuration for Prometheus itself.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]  # Replace with your Prometheus container hostname if needed.

  # Example job to monitor the backend Flask API
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]  # Replace with your Flask container hostname and port.

  # Example job to monitor the frontend React service
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:80"]  # Replace with your React container hostname and port.

  # Example job to monitor Redis (if used)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]  # Replace with your Redis container hostname and port.
